version: "3.7"
services:
  PhD-YOLO:
    image: alex1075/phd:latest
    volumes:
     - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always
